"""Built-in specialist agents available to the Supervisor."""
from backend.agents.base import AgentDefinition


BUILTIN_AGENTS = [
    AgentDefinition(
        id="supervisor",
        display_name="Supervisor",
        role="Classifies work, selects recipes, routes agents, and enforces guardrails.",
        expertise=["routing", "planning", "risk review", "workflow orchestration"],
        workspace_scope=["personal", "work"],
        allowed_tools=["repo_snapshot", "github_read_file", "github_list_files"],
        can_commit=False,
        can_research_web=False,
        can_create_artifacts=True,
        default_model_policy="balanced",
        approval_profile="always_for_risky_actions",
    ),
    AgentDefinition(
        id="researcher",
        display_name="Researcher",
        role="Researches markets, competitors, references, and source material.",
        expertise=["market research", "competitor analysis", "source synthesis"],
        workspace_scope=["personal", "work"],
        allowed_tools=["github_read_file", "playwright_browse"],
        can_commit=False,
        can_research_web=True,
        can_create_artifacts=True,
        default_model_policy="analysis",
        approval_profile="web_research_allowed",
    ),
    AgentDefinition(
        id="strategist",
        display_name="Strategist",
        role="Turns goals into positioning, launch plans, and decision frameworks.",
        expertise=["product strategy", "positioning", "go-to-market"],
        workspace_scope=["personal", "work"],
        allowed_tools=["github_read_file"],
        can_commit=False,
        can_research_web=False,
        can_create_artifacts=True,
        default_model_policy="balanced",
        approval_profile="standard",
    ),
    AgentDefinition(
        id="architect",
        display_name="Architect",
        role="Designs implementation plans, interfaces, schemas, and technical tradeoffs.",
        expertise=["system design", "API design", "database schema", "integration planning"],
        workspace_scope=["personal", "work"],
        allowed_tools=["repo_snapshot", "github_read_file", "github_list_files"],
        can_commit=False,
        can_research_web=False,
        can_create_artifacts=True,
        default_model_policy="analysis",
        approval_profile="standard",
    ),
    AgentDefinition(
        id="builder",
        display_name="Builder",
        role="Implements approved code and documentation changes.",
        expertise=["full-stack implementation", "tests", "documentation"],
        workspace_scope=["personal", "work"],
        allowed_tools=["github_read_file", "github_list_files", "github_commit_files", "run_tests"],
        can_commit=True,
        can_research_web=False,
        can_create_artifacts=True,
        default_model_policy="balanced",
        approval_profile="commit_guarded",
    ),
    AgentDefinition(
        id="tester",
        display_name="Tester",
        role="Validates behavior, regression risk, and acceptance criteria.",
        expertise=["test design", "regression analysis", "quality gates"],
        workspace_scope=["personal", "work"],
        allowed_tools=["github_read_file", "run_tests"],
        can_commit=False,
        can_research_web=False,
        can_create_artifacts=True,
        default_model_policy="fast",
        approval_profile="standard",
    ),
    AgentDefinition(
        id="security_reviewer",
        display_name="Security Reviewer",
        role="Reviews auth, secrets, policy boundaries, and unsafe tool exposure.",
        expertise=["security review", "secret handling", "permission boundaries"],
        workspace_scope=["personal", "work"],
        allowed_tools=["github_read_file", "secret_scan", "run_tests"],
        can_commit=False,
        can_research_web=False,
        can_create_artifacts=True,
        default_model_policy="analysis",
        approval_profile="security_sensitive",
    ),
    AgentDefinition(
        id="critic",
        display_name="Critic",
        role="Challenges plans, catches gaps, and improves final handoffs.",
        expertise=["review", "risk analysis", "clarity"],
        workspace_scope=["personal", "work"],
        allowed_tools=["github_read_file"],
        can_commit=False,
        can_research_web=False,
        can_create_artifacts=True,
        default_model_policy="analysis",
        approval_profile="standard",
    ),
    AgentDefinition(
        id="launch_manager",
        display_name="Launch Manager",
        role="Packages releases, launch checklists, and customer-facing handoffs.",
        expertise=["launch planning", "release packaging", "handoff"],
        workspace_scope=["personal"],
        allowed_tools=["github_read_file"],
        can_commit=False,
        can_research_web=False,
        can_create_artifacts=True,
        default_model_policy="balanced",
        approval_profile="standard",
    ),
    AgentDefinition(
        id="crm_specialist",
        display_name="CRM Specialist",
        role="Plans CRM cleanup, segmentation, lead routing, and enrichment work.",
        expertise=["CRM", "lead routing", "data cleanup", "sales operations"],
        workspace_scope=["work"],
        allowed_tools=["github_read_file"],
        can_commit=False,
        can_research_web=False,
        can_create_artifacts=True,
        default_model_policy="balanced",
        approval_profile="work_data_sensitive",
    ),
    AgentDefinition(
        id="marketing_automation_specialist",
        display_name="Marketing Automation Specialist",
        role="Designs lifecycle campaigns, automations, and attribution workflows.",
        expertise=["marketing automation", "campaigns", "lifecycle journeys"],
        workspace_scope=["personal", "work"],
        allowed_tools=["github_read_file"],
        can_commit=False,
        can_research_web=False,
        can_create_artifacts=True,
        default_model_policy="balanced",
        approval_profile="standard",
    ),
    AgentDefinition(
        id="reporting_analyst",
        display_name="Reporting Analyst",
        role="Creates reporting plans, metric definitions, and dashboard blueprints.",
        expertise=["analytics", "dashboards", "metrics", "data storytelling"],
        workspace_scope=["work"],
        allowed_tools=["github_read_file"],
        can_commit=False,
        can_research_web=False,
        can_create_artifacts=True,
        default_model_policy="analysis",
        approval_profile="work_data_sensitive",
    ),
    AgentDefinition(
        id="sop_digitiser",
        display_name="SOP Digitiser",
        role="Turns operating procedures into workflow apps and checklists.",
        expertise=["process mapping", "workflow design", "SOP transformation"],
        workspace_scope=["work"],
        allowed_tools=["github_read_file"],
        can_commit=False,
        can_research_web=False,
        can_create_artifacts=True,
        default_model_policy="balanced",
        approval_profile="work_data_sensitive",
    ),
    AgentDefinition(
        id="finance_support_agent",
        display_name="Finance Support Agent",
        role="Prepares finance support workflows, summaries, and review packs.",
        expertise=["finance operations", "review packs", "spreadsheet workflows"],
        workspace_scope=["work"],
        allowed_tools=["github_read_file"],
        can_commit=False,
        can_research_web=False,
        can_create_artifacts=True,
        default_model_policy="analysis",
        approval_profile="work_data_sensitive",
    ),
    AgentDefinition(
        id="knowledge_librarian",
        display_name="Knowledge Librarian",
        role="Organizes internal knowledge, documentation, and reusable references.",
        expertise=["knowledge bases", "documentation", "taxonomy"],
        workspace_scope=["personal", "work"],
        allowed_tools=["github_read_file", "github_list_files"],
        can_commit=False,
        can_research_web=False,
        can_create_artifacts=True,
        default_model_policy="fast",
        approval_profile="standard",
    ),
]
